//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTimeOrganization
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public Author()
        {
            this.Tasks = new HashSet<Task>();
            this.News = new HashSet<News>();
        }
    
        public int Author_ID { get; set; }
        public string Author_Name { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<News> News { get; set; }
    }
}
