//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTimeOrganization
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int News_ID { get; set; }
        public string News_Title { get; set; }
        public string News_Content { get; set; }
        public System.DateTime News_Creation_Date { get; set; }
        public int Author_ID { get; set; }
        public Nullable<int> News_Data_id { get; set; }
    
        public virtual Author Author { get; set; }
    }
}
