//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTimeOrganization
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReminderHour
    {
        public int Reminder_Hour_ID { get; set; }
        public int Reminder_Hour { get; set; }
        public int Task_ID { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
