//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTimeOrganization
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Notes = new HashSet<Note>();
            this.ReminderHours = new HashSet<ReminderHour>();
        }
    
        public int Task_Id { get; set; }
        public string Task_Title { get; set; }
        public string Task_Content { get; set; }
        public string Priority_ID { get; set; }
        public int State_ID { get; set; }
        public int Author_ID { get; set; }
        public Nullable<int> Type_ID { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public System.DateTime Date_Day { get; set; }
        public System.DateTime Date_Time { get; set; }
        public string Location_Name { get; set; }
        public Nullable<int> Data_id { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual ICollection<ReminderHour> ReminderHours { get; set; }
        public virtual State State { get; set; }
        public virtual Type Type { get; set; }
    }
}
