//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTimeOrganization
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_schedule
    {
        public string FN { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> schedule_date { get; set; }
        public string post_type { get; set; }
        public string post_title { get; set; }
        public string post_description { get; set; }
        public string post_location { get; set; }
    }
}
